#		RULES FOR MAKING NEW MAPS :
#
#		ALL "ENTRANCES" MUST BE AT [0, 0] - Will connect to exit tile. You can see coords in bottom left when drawing tiles
#
#		DONT GO NORTHWEST FROM ENTRANCE TILE - YOU MAY COLLIDE WITH OTHER MAPS
#		& DON'T BUILD SOUTHEAST OF YOUR EXIT TILE
#
#		ANY "MARKER TILES" (ENEMY SPAWN, EXIT, ETC.) SHOULD BE ON A SEPARATE TILEMAPLAYER AND BE THE FIRST CHILD
#
#
